#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/of.h>                   /* For DT*/
#include <linux/platform_device.h>      /* For platform devices */
#include <linux/input.h>
#include <linux/input-polldev.h>

 struct input_polled_dev *poll_dev;
 bool sema = 1;

static void polled_btn_open(struct input_polled_dev *poll_dev)
{
    /* struct poll_btn_data *priv = poll_dev->private; */
    printk("polled device opened()\n");
}

static void polled_btn_close(struct input_polled_dev *poll_dev)
{
    /* struct poll_btn_data *priv = poll_dev->private; */
    printk("polled device closed()\n");
}

static void polled_btn_poll(struct input_polled_dev *poll_dev1)
{
	 printk("polled function called\n");
	if(sema==1)
	{
    		input_report_key(poll_dev->input, BTN_0, 0);
		sema = 0;		
	}
	else if(sema==0)
	{
    		input_report_key(poll_dev->input, BTN_0, 1);
		sema = 1;
	}
    input_sync(poll_dev->input);
}

static const struct of_device_id btn_dt_ids[] = {
    { .compatible = "g547,input-polled-button", },
    { /* sentinel */ }
};

static int polled_btn_probe(struct platform_device *pdev)
{
   
    struct input_dev *input_dev;
    int ret;

    
    poll_dev = input_allocate_polled_device();
    if (!poll_dev)
        return -ENOMEM;

    
    poll_dev->poll_interval = 200; /* Poll every 200ms */
    poll_dev->poll = polled_btn_poll;
    poll_dev->open = polled_btn_open;
    poll_dev->close = polled_btn_close;
    
    input_dev = poll_dev->input;
    input_dev->name = "G547 input polled Btn";
    input_dev->dev.parent = &pdev->dev;

    /* Declare the events generated by this driver */
    set_bit(EV_KEY, input_dev->evbit);
    set_bit(BTN_0, input_dev->keybit); /* buttons */

    ret = input_register_polled_device(poll_dev);
    if (ret) {
        printk("Failed to register input polled device\n");
        input_free_polled_device(poll_dev);
        return ret;
    }

    return 0;
}

static int polled_btn_remove(struct platform_device *pdev)
{
	input_unregister_polled_device(poll_dev);
    	input_free_polled_device(poll_dev);
	return 0;
}

static struct platform_driver mypdrv = {
    .probe      = polled_btn_probe,
    .remove     = polled_btn_remove,
    .driver     = {
        .name     = "input-polled-button",
        .of_match_table = of_match_ptr(btn_dt_ids),  
        .owner    = THIS_MODULE,
    },
};
module_platform_driver(mypdrv);



MODULE_LICENSE("GPL");
MODULE_AUTHOR("John Madieu <john.madieu@gmail.com>");
MODULE_DESCRIPTION("Polled input device");
